config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get     '/about',     to: 'static_pages#about'
  get     '/signup',    to: 'users#new'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get     '/sociallogin', to: redirect('/auth/google_oauth2')
  get     'auth/:provider/callback', to: 'social_authentication#create'
  get     'auth/failure',   to: redirect('/')
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    attr_accessor :remember_token, :activation_token
    before_save   :downcase_email
    before_create :create_activation_digest  
    validates :name, presence: true, length: {maximum: 50}, uniqueness: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 250}, uniqueness: { case_sensitive: false },format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def feed
      Micropost.where("user_id = ?", id)
    end

    def self.find_or_create_from_auth_hash(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.first_name + " " + auth.info.last_name
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.email = auth.info.email
        user.picture = auth.info.image
        user.password = SecureRandom.urlsafe_base64
        user.save!
      end
    end
  
    private

      def User.new_token
        SecureRandom.urlsafe_base64
      end

      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end

      def authenticated?(attribute,token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
    # Converts email to all lower-case.
      def downcase_email
        self.email = email.downcase
      end

      # Creates and assigns the activation token and digest.
      def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
      end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper  

  private
    def logged_in_user
      if !logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
    def create
        @micropost = current_user.microposts.build(micropost_params)  
        if  @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home'
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer  ||  root_url
    end

    private
        def micropost_params
            params.require(:micropost).permit(:content)
        end

        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
          end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_back_or @user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/social_authentication_controller.rb
class SocialAuthenticationController < ApplicationController
    def create
        @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
        session[:user_id] = @user.id 
        redirect_to @user
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.paginate(per_page: 10,page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      User.delete(@user.id)
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in? 
        !current_user.nil?
    end
    def current_user?(user)
        user == current_user
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end    
    
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/social_authentication_helper.rb
module SocialAuthenticationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def addTitle(page_title = '')
    base_title = "Basic Facebook"
    if(page_title.empty?)
      base_title
    else 
      page_title + " | " + base_title
    end
  end
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-expand-sm nav-light">
    <div class="project-info mt-3">Project: Basic Facebook<span class="mx-4"></span>Developer: loliFanboy</div>
    <div class="project-info ml-auto mt-3">
        <%= link_to "Source code", "#"%>
        <span class="mx-4"></span>
        <%= link_to "About", "#" %>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-sm navbar-light">
    <%= link_to "BASIC FACEBOOK", root_path, class: "navbar-brand text-white font-weight-bold" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <% if !logged_in? %>
                <li class="nav-item"><%= link_to "Log In", login_path , class: "btn mr-1 text-white"%></li>
                <div class="vertical-divider my-auto"></div>
                <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "btn ml-1 text-white" %></li>
            <% else %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle w-100" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <div class="dropdown-item"><%= link_to "Log Out", logout_path,method: :delete , class: "btn ml-1" %></div>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-item"><%= link_to "Profile", user_path(current_user), class: "btn ml-1"  %></div>
                        <div class="dropdown-item"><%= link_to "Settings", edit_user_path(current_user), class: "btn ml-1" %></div>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= addTitle(yield(:title)) %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if yield(:title) != "Sign up" && yield(:title) != "Log in" %>
      <%= render 'layouts/header' %>
      <div class="container-fluid mainBody px-0">
        <% flash.each do |message_type, message| %>
          <div class="py-2">
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          </div>
        <% end %>
          <div class=""><%= yield %></div>
      </div>
      <%= render 'layouts/footer' %>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <div class="border bg-light px-3 py-3 my-1">
    <div class="row mb-3">
      <div class="col-lg-1 pr-0">
        <%= link_to gravatar_for(micropost.user, size: 40 ), micropost.user %>
      </div>
      <div class="col-lg-11 p-0">
        <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
        <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
          <%= link_to "delete", micropost, method: :delete, data:{  confirm: "You sure?"} %>
        <% end %>
        </span>
      </div>
    </div> 
    <span class="content"><%= micropost.content %></span>
  </div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger font-weight-bold">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="mt-2"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<main class='container'>
	<button class='myButt one'>
		<div class='insider'></div>
		Hover over me
	</button>
</main>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-3 border bg-light dashboard">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-9 pl-2">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
    <div id="mainPage">
      <div class="pageWrapper">
        <h1 class="text-center">BASIC FACEBOOK</p>
        <p>basically our website, just like its name, is a basic version of facebook, but with your contibution it will become better and better every time</p>
        <div class="buttonWrapper w-50 mx-auto">
          <div class="insider"></div>
          <%= link_to "Sign up now", signup_path %>
        </div>
      </div>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1 class="display-4 text-center">Update your profile</h1>
<div class="justify-form mx-auto">
<%= form_for(@user) do |f|  %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="row my-4 align-items-center">
        <div class="col-sm-1"><%= f.label :name, image_tag("user-image.svg") %></div>
        <div class="col-sm-11"><%= f.text_field :name , class: "form-control form-control-lg" %></div>
    </div>
    <div class="row my-4 align-items-center">
        <div class="col-sm-1"><%= f.label :email, image_tag("email-image.svg") %></div>
        <div class="col-sm-11"><%= f.email_field :email, class: "form-control form-control-lg" %></div>
    </div>
    <div class="row my-4 align-items-center">
        <div class="col-sm-1"><%= f.label :password, image_tag("password-image.svg") %></div>
        <div class="col-sm-11"><%= f.password_field :password, class: "form-control form-control-lg" %></div>
    </div>
    <div class="row my-4 align-items-center">
        <div class="col-sm-1"><%= f.label :password_confirmation, image_tag("password-image.svg") %></div>
        <div class="col-sm-11"><%= f.password_field :password_confirmation, class: "form-control form-control-lg" %></div>
    </div>
    <%= f.submit "Save changes",class: "btn btn-lg btn-primary d-block mx-auto" %>
<% end %>
<div class="gravatar_edit">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,"Sign up") %>
<div class="background-picture">
    <div class="border border-light justify-form mx-auto incMargin narrowPadding formBorder">
        <h3 class="text-center my-3 display-4">Basic Facebook</h3>
        <div class="row">
            <div class="col-sm">
                <div class="mt-3">
                    <p class="text-center my-2">Or connect with</p>
                    <div class="borderBottom"></div>
                    <a href="#" class="w-100 btn btn-outline-primary my-2"><%= image_tag("facebook-brands.svg",style: "vertical-align:middle") %>
                        <span class="mx-2">Facebook</span>
                    </a>
                    <a href="/auth/google_oauth2" class="w-100 btn btn-outline-primary my-2"><%= image_tag("google-brands.svg",style: "vertical-align:middle") %>
                        <span class="mx-2">Google</span>
                    </a>
                    <a href="#" class="w-100 btn btn-outline-primary my-2"><%= image_tag("github-brands.svg",style: "vertical-align:middle") %>
                        <span class="mx-2">Github</span>
                    </a>
                </div>
            </div>
            <div class="col-sm">
                <%= form_for(@user) do |f| %>
                    <%= render 'shared/error_messages', object: f.object %>
                    <%= f.text_field :name, placeholder: "Full name", class: "my-3 inputForm" %>
                    <%= f.email_field :email, placeholder: "Email address", class: "mb-3 inputForm" %>
                    <%= f.password_field :password, placeholder: "New password", class: "mb-3 inputForm" %>
                    <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "mb-3 inputForm" %>
                    <%= f.submit "Sign up", class: "btn btn-primary w-100 font-weight-bold" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div class="row border border-left-0 w-75 ml-4  profile">
    <div class="col-sm-3 ml-0 pl-0"><%= gravatar_for(@user,size: 200) %></div>
    <div class="col-sm-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>